### ISSUE TITLE
Sys::Hostname does not take any arguments anymore

### ISSUE THREAD

**Issue by eserte** [nigelhorne/CGI-Info#7]
Starting with perl 5.27.5, Sys::Hostname::hostname dies if called with extra arguments. This also happens if the hostname function is called as a class method (`Sys::Hostname->hostname`). This actually happens in CGI::Info.

**Comment by eserte** [comment]
A possible patch is available at cpan.metacpan.org/authors/id/S/SR/SREZIC/patches/CGI-Info-0.64-issue7.patch

**Comment by nigelhorne** [comment]
Thanks for the bug report.

Fixed in commit 804dd1459dd0382856a5d2ed5044b891e8314e14.
